### ISSUE TITLE
Hi team, Do you have some install docs on this repo

### ISSUE THREAD

**Issue by xiaods** [msopentechcn/open-hackathon#484]
we are working on it, and found the docs is not easy to reading. anyone can guide me?

**Comment by xiaods** [comment]
just like PR https://github.com/msopentechcn/open-hackathon/commit/d13e6f8e1412f434b50079bd187071b7d4c62fd9

we would like someone can guide our team to collaboration on this open project

**Comment by juniwang** [comment]
I'm sorry that the document is outdated. I will update it today and this weekend. Hope it helps.

**Comment by xiaods** [comment]
@juniwang Cool. Thanks
