### ISSUE TITLE
how to used customized cloud service 

### ISSUE THREAD

**Issue by zsynacl** [msopentechcn/open-hackathon#652]
Is there any documents about how to use customized cloud service?

we have our own cloud platform, so we want to use this platform in open-hackathon. But I could't explore the logic flow of open-hachathon because I could't use Azure or Alauda currently.

thanks in advance

**Comment by juniwang** [comment]
Sorry we don't have documents about this. You have to implement by yourselves. The architecture allows you to do deployment on any cloud other than azure or alauda
